services:
  db:
    image: postgres:latest
    container_name: pg-container
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 1s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: jbrilha/goethe:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goethe-container
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres-data:
