version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg-container
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: goethe-container
    ports:
      - "8081:8081"
    depends_on:
      - db
    env_file:
      - .env.docker
    # environment:
    #   PORT: ${PORT}
    #   JWT_SECRET: ${JWT_SECRET}
    #   DB_HOST: ${PG_HOST}
    #   PG_USER: ${PG_USER}
    #   PG_PASSWORD: ${PG_PASSWORD}
    #   PG_DB: ${PG_DB}
    #   PG_SSL: ${PG_SSL}
    #   PG_CONN: ${PG_CONN}
    volumes:
      - .:/app
    command: ["./goethe"]

volumes:
  postgres-data:

