// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Alert(alertMsg string, timed bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"alert\" class=\"m-1 bg-white border-black border-2 p-2 text-lg w-fit max-w-xs flex items-stretch justify-between fade\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if timed {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" _=\"on load\n                wait 5s\n                add .fade-hidden to me\n                wait 0.4s \n                remove me\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("><p id=\"alert-msg\" class=\"pr-2 font-bold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(alertMsg)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/alerts.templ`, Line: 19, Col: 13}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><button id=\"close-button\" class=\"h-full flex-grow-0 px-2 btn-black\" type=\"button\" _=\"on click \n                    add .fade-hidden to my.parentElement\n                    wait 0.4s \n                    remove my.parentElement\">&times;</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

// p _="on load if my.textContent.length > 34 then add .border-b to the next <button/>"

// button class="h-full flex-grow-0 px-2 border-l border-black hover:font-bold hover:bg-black hover:text-white"

// div class="m-1 bg-gray-300 shadow-2xl border-2 border-black p-2 text-lg w-fit max-w-xs flex items-stretch justify-between fade"
